### ISSUE TITLE
some figures used in the talks are missing 

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/course#46]
just was trying to get a glimpse of https://github.com/datalad-handbook/course/blob/0b26cb6ac9a5d6c2d5bd5473a92d0284d959ec79/talks/hhu.html but it seems that most of the figures, such as e.g. `talks/hhu.html:        <img height="850" class="fragment fade-in" src="../pics/ukb_datasets.svg">` are nowhere to be found.

**Comment by adswa** [comment]
I added this figure now. I guess I haven't yet because it was an illustration from a paper that wasn't published until last Friday. But I probably also forgot a lot of images - please ping me if there are more.
