### ISSUE TITLE
public url for pics/slides?

### ISSUE THREAD

**Issue by yarikoptic** [datalad-handbook/course#48]
got interested in `sandwhich03.svg` which comes from that submodule but that submodule has ssh url for it

```
(git)lena:~datalad/datalad-handbook/course[master]git
$> datalad -f json_pp subdatasets pics/slides
{
  "action": "subdataset",
  "gitmodule_name": "pics/slides",
  "gitmodule_url": "kumo.ovgu.de:/home/mih/public_html/datalad/slides",
  "gitshasum": "76882e01a9194444b507491889e7d9f6d6dcb6b2",
  "parentds": "/home/yoh/proj/datalad/datalad-handbook/course",
  "path": "/home/yoh/proj/datalad/datalad-handbook/course/pics/slides",
  "refds": "/home/yoh/proj/datalad/datalad-handbook/course",
  "state": "absent",
  "status": "ok",
  "type": "dataset"
}
```

**Comment by adswa** [comment]
I pushed the pics I had access to to the more modern version of this repo at https://github.com/datalad-handbook/datalad-course
This submodule died, the files are directly added

**Comment by yarikoptic** [comment]
Thanks!  FWIW having both https://github.com/datalad-handbook/datalad-course/ and https://github.com/datalad-handbook/course/ is a bit confusing for old minds ;)

**Comment by adswa** [comment]
I know but I want archived links to resolve, and this one has a deprecation notice. maybe I should archive it
